version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    image: djangoapp:app
    container_name: django_container 
    command: python manage.py runserver 0.0.0.0:8000

