# Generated by Django 5.1.1 on 2025-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cotreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_longs', models.IntegerField()),
                ('symbol_shorts', models.IntegerField()),
            ],
        ),
    ]
